# Generated by Django 2.0 on 2018-01-24 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("reader", "0002_auto_20180121_2347")]

    operations = [
        migrations.CreateModel(
            name="Favorite",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=128)),
                ("directory_path", models.CharField(max_length=512)),
            ],
        )
    ]
