# Generated by Django 2.0 on 2018-01-24 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("reader", "0003_favorite")]

    operations = [
        migrations.AlterModelOptions(name="favorite", options={"ordering": ["title"]}),
        migrations.AlterField(
            model_name="bookmark", name="title", field=models.CharField(max_length=128)
        ),
        migrations.AlterField(
            model_name="favorite", name="title", field=models.CharField(max_length=128)
        ),
    ]
