# Generated by Django 2.0 on 2018-05-16 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("reader", "0005_fileitem")]

    operations = [
        migrations.RemoveField(model_name="bookmark", name="comic_path"),
        migrations.RemoveField(model_name="bookmark", name="title"),
        migrations.AddField(
            model_name="bookmark",
            name="comic",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="reader.FileItem",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="bookmark",
            name="page_num",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
