# Generated by Django 2.0 on 2019-02-07 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0006_auto_20180516_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileitem',
            name='file_type',
            field=models.CharField(blank=True, choices=[('comic', 'comic'), ('video', 'video'), ('directory', 'directory')], max_length=12),
        ),
        migrations.AlterField(
            model_name='fileitem',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='reader.FileItem'),
        ),
    ]
