# Generated by Django 2.2.10 on 2020-04-19 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0008_auto_20200419_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='comic',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='reader.FileItem'),
        ),
    ]
