# Generated by Django 3.0.8 on 2020-08-02 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reader", "0009_auto_20200419_1918"),
    ]

    operations = [
        migrations.AddField(
            model_name="fileitem",
            name="furthest_read_page",
            field=models.IntegerField(null=True),
        ),
    ]
