# Generated by Django 3.0.8 on 2020-08-05 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reader", "0011_auto_20200802_1023"),
    ]

    operations = [
        migrations.AddField(
            model_name="fileitem",
            name="is_read",
            field=models.BooleanField(default=False),
        ),
    ]
