# Generated by Django 4.0.3 on 2022-03-28 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reader", "0013_auto_20201219_0912"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fileitem",
            name="file_type",
            field=models.CharField(
                choices=[("comic", "comic"), ("directory", "directory")],
                db_index=True,
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name="fileitem",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
