# Generated by Django 4.0.3 on 2026-05-11 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0015_fileitem_is_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileitem',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
