version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.8.3

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv env
            ./env/bin/pip install -r requirements.txt

      - save_cache:
          paths:
            - ./env
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      # TODO: enable tests when there are tests to run
#      - run:
#          name: run tests
#          command: |
#            ./env/bin/pytest
#
#      - store_artifacts:
#          path: test-reports
#          destination: test-reports
